/*Creation des utilisateurs, et assignation a leur TABLESPACE*/
DROP USER DL101 CASCADE;
DROP USER papyrus CASCADE;

CREATE USER DL101 IDENTIFIED BY afpa DEFAULT TABLESPACE USERS;
GRANT CONNECT, RESOURCE TO DL101;
CREATE USER papyrus IDENTIFIED BY afpa DEFAULT TABLESPACE USERS;
GRANT CONNECT, RESOURCE TO papyrus;

/*Creation des droit SELECT, premirere partie de l'exercice*/
/*
GRANT SELECT ON papyrus.* TO DL101;
*/

/*On donne des privileges a DL101 des tables de papyrus*/
GRANT ALL PRIVILEGES ON PAPYRUS.ENTCOM TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.FOURNIS TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.LIGCOM TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.PRODUIT TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.VENTE TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.ENTCOM_NUMCOM TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.PRODUIT_CODART TO DL101;