/*1 - Creation des utilisateurs, et assignation a leur TABLESPACE*/
CREATE USER DL101 IDENTIFIED BY afpa DEFAULT TABLESPACE USERS;
CREATE USER papyrus IDENTIFIED BY afpa DEFAULT TABLESPACE USERS;

/*2 - Utiliser le script creation des tables de papyrus*/

/*Creation des droit SELECT*/
/*
GRANT SELECT ON papyrus.* TO DL101;
*/

/*3 - On donne des privileges a DL101 des tables de papyrus*/
/*
GRANT ALL PRIVILEGES ON PAPYRUS.ENTCOM TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.FOURNIS TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.LIGCOM TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.PRODUIT TO DL101;
GRANT ALL PRIVILEGES ON PAPYRUS.VENTE TO DL101;
*/
